# Generated by Django 3.2.6 on 2021-08-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210819_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_range',
            field=models.CharField(max_length=254),
        ),
    ]
