# Generated by Django 3.2.6 on 2021-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_size_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_range',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
